In [16]:
import pandas as pd
tabela = pd.read_csv('spotifydataset.csv')

In [17]:
tabela

,Unnamed: 0,artist_name,genres,followers,artist_popularity,artist_url,track_name,album_name,release_date,duration_ms,...,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,0,Ariana Grande,pop,98934105,89,https://open.spotify.com/artist/66CXWjxzNUsdJx...,we can't be friends (wait for your love),eternal sunshine,2024-03-08,228639,...,0.646,5,-8.334,1,0.0427,0.0615,0.000030,0.0740,0.295,115.842
1,1,Ariana Grande,pop,98934105,85,https://open.spotify.com/artist/66CXWjxzNUsdJx...,the boy is mine,eternal sunshine,2024-03-08,173639,...,0.630,7,-5.854,0,0.0434,0.1570,0.000000,0.0732,0.447,97.998
2,2,Ariana Grande,pop,98934105,83,https://open.spotify.com/artist/66CXWjxzNUsdJx...,intro (end of the world),eternal sunshine,2024-03-08,92400,...,0.362,10,-9.480,1,0.0416,0.6700,0.000000,0.1760,0.385,84.726
3,3,Ariana Grande,pop,98934105,80,https://open.spotify.com/artist/66CXWjxzNUsdJx...,Save Your Tears (Remix) (with Ariana Grande) -...,After Hours (Deluxe),2020-03-20,191013,...,0.825,0,-4.645,1,0.0325,0.0215,0.000024,0.0936,0.593,118.091
4,4,Ariana Grande,pop,98934105,79,https://open.spotify.com/artist/66CXWjxzNUsdJx...,"yes, and?",eternal sunshine,2024-03-08,214994,...,0.775,1,-6.614,1,0.0548,0.1900,0.000065,0.1130,0.787,118.998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",2769972,69,https://open.spotify.com/artist/1G9G7WwrXka3Z1...,Roses,Speakerboxxx/The Love Below,2003,369573,...,0.708,0,-5.653,1,0.0545,0.0482,0.000018,0.1070,0.509,108.970
996,996,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",2769972,64,https://open.spotify.com/artist/1G9G7WwrXka3Z1...,Rosa Parks,Aquemini,1998-09-29,324373,...,0.701,6,-7.198,0,0.2830,0.1050,0.000000,0.7610,0.251,103.890
997,997,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",2769972,60,https://open.spotify.com/artist/1G9G7WwrXka3Z1...,B.O.B. - Bombs Over Baghdad,Stankonia,2000-10-31,304226,...,0.978,9,-5.324,1,0.0978,0.0555,0.000041,0.0260,0.653,153.809
998,998,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",2769972,59,https://open.spotify.com/artist/1G9G7WwrXka3Z1...,Da Art of Storytellin' (Pt. 1),Aquemini,1998-09-29,222653,...,0.856,2,-5.833,1,0.2350,0.1070,0.000000,0.7450,0.402,103.773
999,999,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",2769972,58,https://open.spotify.com/artist/1G9G7WwrXka3Z1...,Player's Ball,Southernplayalisticadillacmuzik,1994-04-26,261266,...,0.764,1,-6.304,1,0.2460,0.0398,0.000000,0.4250,0.578,93.071

In [18]:
tabela2 = tabela[(tabela['loudness'] < -6) & (tabela['loudness'] > -8)]

In [19]:
tabela3 = pd.DataFrame(tabela2.groupby('artist_name')['artist_name'].count())
tabela3.index.name = "index_artist"
tabela3

                        artist_name
index_artist
A                                12
A Boogie Wit da Hoodie            4
A Day To Remember                 1
A$AP Ferg                         2
A$AP Rocky                        4
...                             ...
Young Thug                        3
aespa                             1
Â                                 2
Ã                                 1
Å                                 2

[76 rows x 1 columns]

In [22]:
tabela3.sort_values(by='artist_name',ascending=False)

                          artist_name
index_artist
A                                  12
Arijit Singh                        7
Alex Warren                         6
Alice In Chains                     6
Halsey                              6
...                               ...
Novo Amor                           1
The Alchemist                       1
The All-American Rejects            1
aespa                               1
Ã                                   1

[76 rows x 1 columns]